services:

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./app/code:/var/www/html
      - ./web/config/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - webnet
    depends_on:
      - app

  app:
    image: poojanerkar/my-blog-app:latest
    volumes:
      - ./app/code:/var/www/html
    networks:
      - webnet
      - dbnet
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  db:
    image: poojanerkar/my-blog-db:latest
    env_file:
      - .env
    volumes:
      - vol1:/var/lib/mysql
    networks:
      - dbnet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  webnet:
  dbnet:

volumes:
  vol1: